### ISSUE TITLE
GPL Licensing Statement in FAQ

### ISSUE THREAD

**Issue by ddiakopoulos** [sixtyfpsui/sixtyfps#184]
https://github.com/sixtyfpsui/sixtyfps/blob/master/FAQ.md#licensing

IANAL but this statement: _"You can still release your own source code under a permissive license such as BSD, MIT, or Apache license. Only binary distribution needs to comply to the terms of the GPL. It is up to those who want to distribute a non-free version of the application to acquire a commercial license."_ is incorrect. 

Any codebase that chooses to incorporate GPL code requires that the derivative codebase also be licensed under GPL which is why it's colloquial referred to as a _viral license_. Source-code distribution absolutely needs to adhere to the GPL license.

**Comment by ogoffart** [comment]
It is my understanding that only the combined work need to be under the GPL, which means indeed that a program using the GPL version of SixtyFPS is a combined work, and its entire codebase must be provided under the term of the GPL. (that's the so-called virality)
However, AFAIK, nothing prevents you to have file within that codebase under a **more permissive** license.

Let's take an example: Let's imagine an application Fizzbuzz, which is using SixtyFPS. The code of Fizzbuzz would be released under MIT. But the Fizzbuzz application itself should be released under the GPL to comply with the license. But a third party entity could use the SixtyFPS under a commercial license, and take the code of Fizzbuzz which is MIT and release a proprietary application derived of Fizzbuzz.  
The use case would be more if one were to write a library called Libfizzbuzz which is provided under MIT although in order to use that library one must also use SixtyFPS which means either acquiring a license, or releasing the final product under GPL.

Maybe the wording in the FAQ is not ideal but this is what it tries to convey.
Do you see any flaw in my reasoning?

**Comment by ddiakopoulos** [comment]
Hi @ogoffart I think that's a misunderstanding. If you take Section 5 (c) from [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) it reads

> You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of Section 4, provided that you also meet all of these conditions: ...

> c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable Section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it. ... A compilation of a covered work with other separate and independent works, which are not by their nature extensions of the covered work, and which are not combined with it such as to form a larger program, in or on a volume of a storage or distribution medium, is called an "aggregate" if the compilation and its resulting copyright are not used to limit the access or legal rights of the compilation's users beyond what the individual works permit. Inclusion of a covered work in an aggregate does not cause this License to apply to the other parts of the aggregate.

More information can be found in summary form on [Wikipedia](https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works). The long and the short of it is that any derivative work (binary or source) that includes any GPLv3 code (such as SixtyFPS) must also be released under the GPLv3 to be compatible with the terms of that license.

No author or maintainer of a permissively licensed software application or library can use SixtyFPS without being bound by the terms of the GPLv3 _unless_ they purchase a commercial license from you. In that case, those customers would be bound by the terms of your commercial license and you _may_ permit them to release the rest of their codebase under a different non-GPL license.

**Comment by ogoffart** [comment]
Hi @ddiakopoulos ,  thanks for your comments.

I am still convinced it is allowed to combine more permissive licences that are compatible with the GPL, and the GPL.  Sure, in the end, the final product must be released under the GPL, and all its codebase must therefore be in a license compatible with the GPL.  But I don't see anything that prevent using more permissive licenses for some parts.

> No author or maintainer of a permissively licensed software application or library can use SixtyFPS without being bound by the terms of the GPLv3 [...]

That is true. But since this permissively licensed software is understood to be in a license compatible with the GPL, It should be OK to release part of their codebase under such license, which give more rights than the GPL.
These extra right would allow someone holding a commercial license of SixtyFPS to re-use their code without being bound to the GPL, or would allow someone to re-use part of the source code of this application in another commercial application, that does not use SixtyFPS. 

As an example, i remember kdelibs 3.x being LGPL (more permissive) while it was based on Qt which was GPLv2 at the time.
You will also find some source file in the linux kernel that are under the MIT, Apache or BSD license: https://github.com/torvalds/linux/blob/master/drivers/power/reset/ocelot-reset.c / https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/i915/i915_pmu.c 

Perhaps I should mention that the source code should be dual licensed with GPL, but i think that goes without saying.

**Comment by ogoffart** [comment]
I made a small change to the wording in the FAQ, I hope it clarifies the situation.
Does that reads better?

This sentence you quoted from the license make me confident that my interpretation is correct:

> This License gives no permission to license the work in any other way, **but it does not invalidate such permission if you have separately received it**. 

In this case, the "separately received it" would be the combination of the MIT or BSD license header in the source code of the app/library, and the SixtyFPS commercial license.

**Comment by ogoffart** [comment]
Is the new wording in the FAQ sufficient? Can I close this issue?

Regardless, it is our intention to make it possible for libraries or applications authors or  to write BSD or MIT code that uses SixtyFPS, and the distribution of their code in source form can be done using any permissive license, such that it should be possible for a third party to purchase a SixtyFPS license if they want to release a non-free version of the software.
If the GPL does not allow that (and i believe it does allow it), we would make sure to add an exception, or to make it possible via the dual licensing.

May I ask if you are interested to use SixtyFPS from a permissive license code base?

**Comment by ams** [comment]
For a good read on license compatibility (instead of randoms on the internet), and how you can combine works:
https://www.gnu.org/licenses/license-compatibility.en.html but in this case, https://www.gnu.org/licenses/gpl-faq.en.html#GPLWrapper might also be useful.
