### ISSUE TITLE
Errors when using Native style

### ISSUE THREAD

**Issue by Sycration** [sixtyfpsui/sixtyfps#189]
When I try to run this example using the native styling: 
`import { Button } from "sixtyfps_widgets.60";
export HelloWorld := Window {
    width: 100px;
    height: 25px;
    Button {
        width: parent.width;
        height: parent.height;
        text: "Click Me";
        clicked => { self.text = "Clicked"; }
    }
}`
and the rust 
`sixtyfps::include_modules!();
fn main() {
    HelloWorld::new().run();
}`

I get these errors!
[error.txt](https://github.com/sixtyfpsui/sixtyfps/files/6146072/error.txt)

This is annoying as Qt looks good.

**Comment by ogoffart** [comment]
This kind of error happens if the Qt backend (`sixtyfps-rendering-backend-qt`) is not enabled. This happens if the build script for couldn't find Qt. Do you see any warning when building sixtyfps-rendering-backend-qt?
This page has information on how to install Qt https://github.com/sixtyfpsui/sixtyfps/blob/master/docs/install_qt.md
What platform are you on?

Clearly we need to improve the error message when this happens.
