### ISSUE TITLE
Flickable with layout and in layout propagates wrong constraints

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#194]
The following test-case renders incorrectly at least on Windows:

```
export Test := Window {
    VerticalLayout {
        Flickable {
            VerticalLayout {
                for i in 6: Text {
                    text: "Test";
                }
            }
        }
    }
}
```

Either the six Text elements aren't visible or, when trying to resize the window with the mouse cursor, the window becomes super small:

https://user-images.githubusercontent.com/1486/114379009-999d1c00-9b88-11eb-89cf-a6f7a3da0a8f.mov

**Comment by ogoffart** [comment]
Here is a even smaller testcase

```css
Test := Window {
    outer := HorizontalLayout {
        Flickable {
            inner := VerticalLayout {
                Text { text: "Test";  }
            }
        }
    }
}
```

The problem here is that the maximum size will be temporary 0. 

Here is what happens:

 - The `flickable` pass sets a fake property binding on the flickable:  `maximum-width: inner.maximum-width;`  (and same for height). It will also generate an intermediate viewport Rectangle
 - the `materialize_fake_properties` pass will then make sure these property exist at runtime.
 - The `lower_layout` will see two independent layout, because the intermediate rectangle "cuts" the layout pass. This is overall desirable because we want special rules for the Flickable, but this will be a problem for the ordering.
 - The `lower_layout` pass will make a cell in the outer layout that depends on the `flickable.maximum-width`
 - The `lower_layout` pass set the information so that when the layout info for the inner layout is computed, it sets the `  inner.maximum-width` property.
 - But the generator or the interpreter will consider the two layout as separate and will handle the outer layout first, before the inner layout. So at the time the info for the outer layout is computed, the inner.maximum-width has not been set and is 0 by default.
 - As a result, we end up with a maximum size of 0,0 for the window.

A maximum size of 0,0 used to make the window disapear, but this is mitigated in commit 6fe2c1f
however, the bug remains.
