### ISSUE TITLE
Viewer should support saving and loading data

### ISSUE THREAD

**Issue by matklad** [sixtyfpsui/sixtyfps#238]
My app makes heavy use of data, which is set by the rust code. For this reason, `viewer` isn't very helpful: without data, there's not much to view! Filling data by hand is tedious (and I failed to do this for an 2d array), it would be cool if I can snapshot the data from my live app, load it into the viewer, and then tweak.

**Comment by ogoffart** [comment]
Yeah, we could have an option to load properties from a json file for example.

**Comment by ogoffart** [comment]
I added the good first issue tag because it should be not too difficult to set these property in viewer/main.rs (https://github.com/sixtyfpsui/sixtyfps/blob/master/tools/viewer/main.rs#L55)
We can simply call [ComponentInstance::set_property](https://docs.rs/sixtyfps-interpreter/0.0.6/sixtyfps_interpreter/struct.ComponentInstance.html#method.set_property) for each property.
One just has to write some code to create the `sixtyfps_interpreter::Value` from the json.

**Comment by tronical** [comment]
This could be used to implement something like https://sanana.kiev.ua/index.php/yad / https://news.ycombinator.com/item?id=28443736
