### ISSUE TITLE
The cursor position is wrong when there are CJK characters in TextInput

### ISSUE THREAD

**Issue by Hentioe** [sixtyfpsui/sixtyfps#363]
![cjk-input](https://user-images.githubusercontent.com/13946976/127553660-3643ce6d-64df-48dc-bda6-507e291c16c5.gif)

Environment: Linux on X11
Font: Noto Snas CJK SC

In fact, there is more than one problem on CJK. I did not find any documentation about CJK. Is there any plan to support CJK in the future?

I am looking forward to the development of this library! 👍

**Comment by hunger** [comment]
One big challenge to get CJK support great will be knowing what it should actually behave like (the same is true for other non-latin languages). Any help on that front would be highly appreciated!

There is no need to fix the actual bugs, but good bug descriptions like this one would be tremendously helpful!

The actual string you are using in your demo so that it can be copy/pasted into the text entry widget would also help to reproduce the actual issue..

**Comment by tronical** [comment]
Thanks for the detailed report (love the animated gif :). Please keep filing bugs you see in CJK usage.

This particular bug happens with the Qt backend, where we instruct Qt to draw the text cursor at the position we calculate. We calculate the position as an offset in the UTF-8 encoded string, while Qt's API expects the position to be an index in the UTF-16 encoded string. In the type system between Rust and Qt that's just an integer, so the indices passed to Qt originate from byte offsets and we do not notice. They are way to "large", thus the cursor appearing too far to the right.

I'll fix that.
