### ISSUE TITLE
Clicking a button, moving mouse off the button, and releasing still triggers action

### ISSUE THREAD

**Issue by nyanpasu64** [sixtyfpsui/sixtyfps#455]
I'm testing `cargo install cargo-ui` (which defaults to the Qt theme) on Linux, with sixtyfps 0.1.1. When I click a button, move my mouse off the button, and release the mouse, the button still triggers. Whereas in other UI toolkits, moving your mouse off a button is a way to cancel a button press.

**Comment by ogoffart** [comment]
Thanks for the bug report

**Comment by Bendrien** [comment]
This change made the usage of the `Slider` very unintuitive. One has to release the mouse while hovering the slider otherwise it will not trigger a `changed` action and reset to the "pressed-value" point.

In general it would be cool to have a consistent way of accessing the mouse position on release similar to the `pressed-x` and `pressed-y` property; maybe with a `released-x` and `released-y` property? These would then have to be updated regardless of hovering the `TouchArea` or not as it was before. As side note the documentation of `pressed-x` seems to be off somewhat.

**Comment by ogoffart** [comment]
Right, I have noticed that the Slider and scrollbars are harder to use as well. I filled #494
