### ISSUE TITLE
Ability to change the Mouse cursor

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#577]
Discussed in https://github.com/sixtyfpsui/sixtyfps/discussions/576

We should add the ability to change the mouse cursor in TouchArea (or possibly on all element?)

```qml
   TouchArea {
      mouse-cursor: pointer;
   }
```

I'm  the `mouse-cursor:` name here, instead of `cursor:` like in CSS in case we extend the property to be used on all elements.

The value should probably be an enum consisting of the keywords from the [CSS spec](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor).
Support for custom cursor could be added later.

**Comment by lukas-jung** [comment]
Hey. I'd like to work on this issue if that's ok.

**Comment by ogoffart** [comment]
@lukas-jung that'd be great, just let me know if you have any questions

**Comment by lukas-jung** [comment]
I've got a first version running with both backends. there are some problems however.
not all css cursors are available in qt:
context-menu
cell
vertical-text
no-drop
all-scroll
zoom-in
zoom-out
and all unidirectional resizes.

Currently i'm replacing no-drop with not-allowed and the unidirectional resizes with their bidirectional counterpart.
All the other cursors can perhaps be added in a later Issue/PR. One could probably "steal" the bitmaps from webbrowsers or something like that.

However there is a second problem with the move cursor: since 'move' is a rust keyword I cannot use it as an enum variant!
Is it possible to map the .60 move to a rust enum variant that has another name?

Or perhaps the rust side of the enums should always use idiomatic camel case variant names and then the snake case .60 enum variants must be properly mapped to those.
