### ISSUE TITLE
Document and test the minimum supported rust version

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#622]
At the moment we require at least 1.54, which is something that we should document and in the CMake build check for, in order to error our early on instead of the build failing later in some unrelated crate.

**Comment by tronical** [comment]
The documentation part is done for C++ as well as the CMake error. We have the option of leaving this ticket open to add the rust-version field to Cargo.toml when we upgrade to edition 2021, or this could be delegate to a separate "edition 2021 todo" ticket (milestone'd to 0.2?).

Do you have any preference about which path to go?

**Comment by ogoffart** [comment]
I don't think edition 2021 or bumping the minimum version require a change in the semver version.
I suggest we just upgrade to the minimum version when we have a need for it because a dependency uses that or if there is a feature we want to use.

(The `rust-version` would be a feature we would want to use, but anything under 1.57 don't make sense for this field)

**Comment by tronical** [comment]
Ok, C++ and Rust docs mention MSRV and a CMake check is in place. I'm closing this as I don't think there's anything actionable left for now.
