### ISSUE TITLE
[PROPOSAL] Move vscode_extention to separate repo

### ISSUE THREAD

**Issue by nagayev** [sixtyfpsui/sixtyfps#629]
Hello. 
It seems to me that this repository should contain only sixtyfps library code. 
Many companies spread their works like this.

**Comment by ogoffart** [comment]
What would be the reason of splitting?

The inconvenient is that it depends on the library code and need to be kept in sync. 
I like the mono-repo approach better. (many companies use a monorepo :-) )
At this point the size of the repository is manageable, but if that becomes a problem, we can give instruction for partial clones.

**Comment by nagayev** [comment]
@ogoffart Okey. It's a matter of your taste.I think monorepos are ugly by design.

**Comment by ogoffart** [comment]
interesting point of view... if not very elaborate.

I think it's not black or white, and there is some level of granularity which is right. For example, having every file in a different repository would be too much, and putting everything in the same repository would also be too much. The question is what it make sense to separate.
And i don't think it make sense to separate the vscode_extension because it is released at the same time as the rest of the library.

**Comment by nagayev** [comment]
@ogoffart okey
