### ISSUE TITLE
Customize StandardListView behavior

### ISSUE THREAD

**Issue by constituent** [sixtyfpsui/sixtyfps#638]
I'm trying sixtyfps-rs 0.1.4 for a hobby project, and I'd like to change some default behaviors of StandardListView. For example, I'd like pressing Up/Down key to decrease/increase `current-item` index of StandardListView.

The solution may not have been documented or even implemented, and it's ok. I'm most concerned about how am I supposed to do this (maybe in a future version of sixtyfps).

I suppose this requires some rust. Unfortunately I failed to quite understand what works under the hood. `sixtyfps_corelib::items::Item` contains a `key_event` method, should/could I implement it for `MyListView(StandardListView)`? Can I use MyListView in 60 files?

**Comment by ogoffart** [comment]
These kind of basic key shortcut should be implemented by default indeed.

One way to do it would be to do it in the .60 files using a FocusScope. I managed to make it work with left and right keys:

```qml
import {  StandardListView } from "sixtyfps_widgets.60";
App := Window {
    sl := StandardListView {
        model: [
            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
        ];
        FocusScope {
            key-pressed(event) => {
                if (event.text == "\u{000E}") { // that's left
                    sl.current-item -= 1;
                } else if (event.text == "\u{000F}") { // that's right
                    sl.current-item += 1;
                }
                accept
            }
         }
    }
}
```

[Live Preview](https://sixtyfps.io/releases/0.1.4/editor/?snippet=import+%7B++StandardListView+%7D+from+%22sixtyfps_widgets.60%22%3B%0AApp+%3A%3D+Window+%7B%0A++++sl+%3A%3D+StandardListView+%7B%0A++++++++model%3A+%5B%0A++++++++++++%7Btext%3A+%22Lorem%22%7D%2C+%7Btext%3A+%22ipsum%22%7D%2C%7Btext%3A+%22dolor%22%7D%2C%7Btext%3A+%22sit%22%7D%2C%7Btext%3A+%22amet%22%7D%2C%7Btext%3A+%22consetetur%22%7D%2C%0A++++++++++++%7Btext%3A+%22Lorem%22%7D%2C+%7Btext%3A+%22ipsum%22%7D%2C%7Btext%3A+%22dolor%22%7D%2C%7Btext%3A+%22sit%22%7D%2C%7Btext%3A+%22amet%22%7D%2C%7Btext%3A+%22consetetur%22%7D%2C%0A++++++++%5D%3B%0A++++++++FocusScope+%7B%0A++++++++++++key-pressed%28event%29+%3D%3E+%7B%0A++++++++++++++++if+%28event.text+%3D%3D+%22%5Cu%7B000E%7D%22%29+%7B+%2F%2F+that%27s+left%0A++++++++++++++++++++sl.current-item+-%3D+1%3B%0A++++++++++++++++%7D+else+if+%28event.text+%3D%3D+%22%5Cu%7B000F%7D%22%29+%7B+%2F%2F+that%27s+right%0A++++++++++++++++++++sl.current-item+%2B%3D+1%3B%0A++++++++++++++++%7D%0A++++++++++++++++accept%0A++++++++++++%7D%0A+++++++++%7D%0A++++%7D%0A%7D%0A%0A%0A#)


The problem is that these internal code are not complete and not documented!, there is no code for up or down arrow.
We indeed had the idea to use control unicode character for special keys in the `text` field of the key event. We'd need to add some for up and down.
If you want to add them, you can add them in input.rs around that line: https://github.com/sixtyfpsui/sixtyfps/blob/master/sixtyfps_runtime/corelib/input.rs#L122 , and the backend need also to be adapted to send the right code.

But that really should be done in ListView itself or at least in StandardListView. (which are implemented in the sixtyfps_compiler/widgets directory)

**Comment by hunger** [comment]
U+E000..U+F8FF is the Private Use Area (PUA) defined by Unicode, which would be a good place to put these special codes.

Maybe we could reuse one of the more standards Non-Standard uses? E.g. Apple inherited some interesting code points from NeXTstep back in the days: https://www.unicode.org/Public/MAPPINGS/VENDORS/APPLE/CORPCHAR.TXT

**Comment by constituent** [comment]
Thanks for the detailed explanation.

In fact I have two questions. One is how to add key shortcut to `StandardListView`, and using `FocusScope` is an acceptable (or maybe idiom?) solution for a user. I agree this should be the default behavior of `StandardListView`. However, there are only .60 files in the sixtyfps_compiler/widgets directory. Do you mean to implement this functionality with `FocusScope`? I believed some rust code are needed. At least `NativeStandardListViewItem` contains an `-is_internal` comment line.

The other question is generally how to create customized widget. For example in Qt, I may define my own class, overriding the keyPressEvent method of QListWidget. With sixtyfps, do this supposed to be done in .60 files alone? Moreover, if I want to add TreeView or TableView, could you give me some guide?

**Comment by ogoffart** [comment]
We currently do not have public API to write item in native language like the native ones. I think it's fine to use a FocusScope and implement that in .60 in the widgets.
If we need we could add a builtin function in native code, but i don't think this is necessary for these shortcut.

**Comment by constituent** [comment]
OK, thanks for the help!
