### ISSUE TITLE
When component has states, the states of the component it is based on do not work.

### ISSUE THREAD

**Issue by farmaazon** [sixtyfpsui/sixtyfps#752]
To reproduce: clone the https://github.com/farmaazon/sixtyfps-bugs and run. You should see the red rectangle in the top-left corner, but actually nothing is visible: apparently no state of `Background` is activated, and the width property remains with `0px` value. When you replace `WithLabel` with `Background` in main.rs line 39, the rectangle is displayed properly.

**Comment by ogoffart** [comment]
Thanks for the bug report. 
I can reproduce the bug and this is indeed an issue. I still don't understand why this happen and i'll investigate next week.

(It seems this bug could happen with inlining because of https://github.com/sixtyfpsui/sixtyfps/blob/ffd651d04c4bd847b961e888a22d214b7e8618bc/sixtyfps_compiler/passes/inlining.rs#L94 , but there should not be inlining at this point so it's probably something else)
