### ISSUE TITLE
Breaking into different repos

### ISSUE THREAD

**Issue by arijit79** [sixtyfpsui/sixtyfps#91]
Ok. I haven't totally studied your entire codebase but I can tell one thing. You should break the project into multiple repositories for each separate language binding. This can help, for example a non C++ contributor to not clone the C++ code. 

For you guys, you may form a organization to manage all projects. I know my idea may seem a little like "What's it worth for", but after working for almost 7 years as a GUI programmer, I have realised that this is the best approach.

Also you can use submodules or subtrees if the code needs to be integrated

**Comment by tronical** [comment]
Hi arijit79! Splitting up the code base into multiple repositories is indeed a valid way to improve scalability, and works relatively well with GitHub.

During my years in Qt I have made the experience however that submodules/subtrees are tedious to coordinate and pull together, especially when releasing but also when doing large refactorings. The ability to quickly apply fixes to an entire code base works best with monolithic repositories and that is a strength I think we benefit from right now more than we suffer from checkout sizes.

It's possible that in the future this project grows to a size that will require a splitting, and then the technologies that you mention, such as subtrees, make it feasible to split.

**Comment by ogoffart** [comment]
We have considered whether to use a single mono-repository or several repository and we went with the mono-repository approach. From experience with both system, and also from the experience of what other big company are doing (e.g. Google and its huge repository), this seems to be the better system. Everything is anyway inter-connected. Lots of small repository cause lots of overhead in synchronizing them and put them back together. Or for example committing patches that changes API across all the different parts.

You mention the problem of  "non C++ contributor to not clone the C++ code." and I sympathize with this problem, however the C++ code is currently very tiny, especially as currently the repository's history is still small. When it grows up, we can consider providing git partial-clone/sparse-checkout profiles for some use case. git tooling regarding partial clone has improved quite a lot in the last years so this should be, in my opinion, easier than the work of putting everything together in the common case.

That said, we do plan to take apart things that are completely independent. For example, we did that already with the small crate https://github.com/sixtyfpsui/pin-weak , and we might separate others crates in the `helper-crates` folder when they are mature and independent enough.

So because we do not plan to split repository at this point, i'm going to close this issue.
That does not mean that we are not open for discussion, thank you, arijit79, for bringing that up.
